-- =============================================================================
-- BM mapping — generated in workspace from local Excel files (2026-03)
-- Sources:
--   Branches: All IR Detail 2026.03.09.xlsx (GENERAL_MGR contains Frankel) → distinct RENT_LOC
--   Employees: March 2026 employee listing.xlsx (Mgr Branch I/II, supervisor chain → Adam Frankel)
-- If UPDATE affects 0 rows, compare org_mapping.branch spacing to IR (e.g. "7401-01    - PERRINE HLE").
-- =============================================================================
--
-- 007_bm_from_employee_listing_frankel.sql
-- Generated by scripts/generate_bm_org_sql.py — review before running in Lakebase.
-- Cluster filter: supervisor_frankel
-- Employee rows after Mgr Branch I/II + cluster: 15
-- Branch rows in CSV: 17
-- Matched (branch, bm) pairs: 17
-- Employees (unique) whose Area not in any branch prefix in CSV: 0

-- Unmatched employees (no branch with same area prefix in CSV):
--

BEGIN;

-- Preview count
-- SELECT COUNT(*) FROM org_mapping o JOIN (...) v ON o.branch = v.branch;

UPDATE org_mapping AS o
SET bm = v.bm, updated_at = now()
FROM (VALUES
    ('5516-04    - PINES EAST HLE', 'Tillett, Nedsky P'),
    ('5562-02    - PEMBROKE PINES WEST HLE', 'Dominguez, Jordan'),
    ('5567-03    - HIALEAH HLE', 'Sanchez, Felipe'),
    ('5599-02    - DAVIE HLE', 'Casado, Carlos E.'),
    ('7401-01    - PERRINE HLE', 'Lumbi, Luis'),
    ('7401-09    - PINECREST HLE', 'Lumbi, Luis'),
    ('7404-13    - MIAMI BEACH HLE', 'Escobar, Stevens'),
    ('7407-01    - CORAL GABLES/S MIAMI HLE', 'Johnson, Mark A'),
    ('7409-04    - MIAMI GARDENS', 'Chirinos, Fidias Enrique (Fidias Chirinos)'),
    ('7414-01    - HOLLYWOOD HLE', 'Willis, Tiffany'),
    ('7414-02    - AC HOTEL AVENTURA MIAMI', 'Willis, Tiffany'),
    ('7420-01    - FT. LAUD DOWNTOWN HLE', 'McClain, Jamar Quintin'),
    ('7466-08    - MIAMI LAKES HLE', 'Aguilar, Javier Francisco'),
    ('7467-09    - DORAL HLE', 'Hoover, Jonathan David'),
    ('7487-10    - MIAMI DT HLE', 'Alaoui, Samir'),
    ('7494-11    - KENDALL HLE', 'Musa, Carlos Juan'),
    ('7498-05    - FT LAUD CENTRAL HLE', 'Knight, Quarina Sharon')
) AS v(branch, bm)
WHERE o.branch = v.branch;

COMMIT;
