/**
 * Onboarding tour step definitions (BM + GM).
 * target: CSS selector for spotlight; null = centered modal
 * requiredView: view ID user must be on; tour will navigate if needed
 * actionType: for interactive gates; replay mode skips gates
 */
export const BM_ONBOARDING_STEPS = [
  {
    id: "welcome",
    target: null,
    requiredView: "bm-dashboard",
    title: "Welcome to LEO",
    content: "Your lead management system, built for how you work. We'll show you around in just a few steps.",
    actionType: null,
  },
  {
    id: "summary",
    target: "[data-onboarding=summary]",
    requiredView: "bm-dashboard",
    title: "Your numbers at a glance",
    content: "Total Leads, Conversion Rate, and Comment Rate — everything you need to track performance.",
    actionType: null,
  },
  {
    id: "metric-drilldown",
    target: "[data-onboarding=metric-drilldown]",
    requiredView: "bm-dashboard",
    title: "Deep-dive any metric",
    content: "Click any tile to see what's behind the number — which leads changed, how you compare to last period, and what's driving the movement.",
    actionType: null,
  },
  {
    id: "view-trends",
    target: "[data-onboarding=view-trends]",
    requiredView: "bm-dashboard",
    title: "See how you're trending",
    content: "Click here to view trends over time and spot patterns.",
    actionType: "view_trends",
  },
  {
    id: "my-leads",
    target: "[data-onboarding=my-leads]",
    requiredView: "bm-dashboard",
    title: "Your leads",
    content: "All leads for your branch. Click any row to open the full profile.",
    actionType: null,
  },
  {
    id: "lead-profile",
    target: "[data-onboarding=lead-row]",
    requiredView: "bm-dashboard",
    title: "Open a lead",
    content: "Click a lead to open their profile — that's where the real work happens.",
    actionType: "click_lead",
  },
  {
    id: "notes",
    target: "[data-onboarding=notes-textarea]",
    requiredView: "bm-lead-detail",
    title: "Add your comments",
    content: "Document your outreach here. Click Update Lead when you're done.",
    actionType: "add_note",
  },
  {
    id: "tasks",
    target: "[data-onboarding=tasks-section]",
    requiredView: "bm-lead-detail",
    title: "Tasks from your GM",
    content: "Assigned tasks show up here. Click one to view details and take action.",
    actionType: "open_task",
  },
  {
    id: "edit-contact",
    target: "[data-onboarding=contact-edit]",
    requiredView: "bm-lead-detail",
    title: "Keep contact info current",
    content: "Click the pencil to update email or phone when customers change details.",
    actionType: "edit_contact",
  },
  {
    id: "sidebar",
    target: "[data-onboarding=sidebar-nav]",
    requiredView: "bm-dashboard",
    title: "Get around quickly",
    content: "Summary, My Leads, and Open Tasks — your main navigation, always one click away.",
    actionType: null,
  },
  {
    id: "inbox",
    target: "[data-onboarding=inbox-button]",
    requiredView: "bm-dashboard",
    title: "Your Inbox",
    content: "When your GM has instructions for a specific lead, they'll appear here.",
    actionType: null,
  },
  {
    id: "done",
    target: "[data-onboarding=help-button]",
    requiredView: "bm-dashboard",
    title: "You're ready to go",
    content: "That's it — you're set up. Use the ? button next to Inbox anytime to revisit this tour.",
    actionType: null,
  },
];

export const GM_ONBOARDING_STEPS = [
  {
    id: "welcome",
    target: null,
    requiredView: "gm-overview",
    title: "Welcome to LEO — Manager View",
    content: "Your zone-level command centre. We'll walk you through the key sections so you can hit the ground running.",
    actionType: null,
  },
  {
    id: "gm-work",
    target: "[data-onboarding=gm-work]",
    requiredView: "gm-overview",
    title: "Your weekly work",
    content: "Meeting Prep and Spot Check — the two things you need every week. Start here before your branch meetings.",
    actionType: null,
  },
  {
    id: "gm-meeting-prep",
    target: "[data-onboarding=gm-meeting-prep]",
    requiredView: "gm-overview",
    title: "Meeting Prep",
    content: "Review each branch's performance before your weekly meeting. Outstanding items show what still needs attention.",
    actionType: null,
  },
  {
    id: "gm-spot-check",
    target: "[data-onboarding=gm-spot-check]",
    requiredView: "gm-overview",
    title: "Spot Check",
    content: "Randomly sample leads across branches to verify data quality and BM follow-through.",
    actionType: null,
  },
  {
    id: "gm-summary",
    target: "[data-onboarding=gm-summary]",
    requiredView: "gm-overview",
    title: "Zone-wide metrics",
    content: "Six key metrics across all your branches. Use the time filter to compare periods and spot movement.",
    actionType: null,
  },
  {
    id: "gm-metric-drilldown",
    target: "[data-onboarding=gm-metric-drilldown]",
    requiredView: "gm-overview",
    title: "Drill into any metric",
    content: "Click any tile to see what's behind the number — branch-level breakdown, period comparison, and what's driving change.",
    actionType: null,
  },
  {
    id: "gm-trends",
    target: "[data-onboarding=gm-trends]",
    requiredView: "gm-overview",
    title: "Trends over time",
    content: "Track any metric over time. Group by branch, insurance company, or status to uncover patterns. Switch between bar, line, and table views.",
    actionType: null,
  },
  {
    id: "gm-team-performance",
    target: "[data-onboarding=gm-team-performance]",
    requiredView: "gm-overview",
    title: "Team performance",
    content: "Leaderboard rankings, activity reports, and compliance scores — everything you need to coach your BMs.",
    actionType: null,
  },
  {
    id: "gm-sidebar",
    target: "[data-onboarding=sidebar-nav]",
    requiredView: "gm-overview",
    title: "Navigate your view",
    content: "Work, Summary, and Team Performance — your main sections, always one click away in the sidebar.",
    actionType: null,
  },
  {
    id: "done",
    target: "[data-onboarding=help-button]",
    requiredView: "gm-overview",
    title: "You're all set",
    content: "That's the tour. Use the ? button anytime to revisit it. Now go run your zone.",
    actionType: null,
  },
];
