-- Hertz LMS - 50 additional mock leads spread across all 15 branches
-- Run after 013_onboarding_completed_at.sql
-- Reservation IDs: HL-2026-001247 through HL-2026-001296

INSERT INTO public.leads (
  customer, reservation_id, status, archived, enrichment_complete,
  branch, bm_name, days_open, mismatch, gm_directive,
  insurance_company, time_to_first_contact, first_contact_by,
  time_to_cancel, hles_reason, last_activity,
  translog, enrichment, enrichment_log, email, phone
) VALUES

-- ── Downtown LA  (J. Smith) ──────────────────────────────────────────
('Angela Rivera', 'HL-2026-001247', 'Rented', false, true,
 'Downtown LA', 'J. Smith', 1, false, null,
 'Geico', '35m', 'branch', null, null,
 '2026-01-21T10:00:00',
 '[{"time":"Jan 21, 10:00 AM","event":"Call","outcome":"Converted"}]'::jsonb,
 '{}'::jsonb, '[]'::jsonb,
 'angela.rivera@example.com', '+14155551001'),

('Marcus Thompson', 'HL-2026-001248', 'Cancelled', false, true,
 'Downtown LA', 'J. Smith', 3, false, null,
 'Progressive', '1h 45m', 'branch', '2d 6h', 'Customer no-show',
 '2026-01-24T14:30:00',
 '[{"time":"Jan 22, 11:00 AM","event":"Call","outcome":"Spoke — confirmed pickup"},{"time":"Jan 24, 2:30 PM","event":"Call","outcome":"No show — left voicemail"}]'::jsonb,
 '{"reason":"No-show after confirmation","notes":"Confirmed pickup Tuesday but never arrived","nextAction":"Call again","followUpDate":"Feb 1, 2026"}'::jsonb,
 '[]'::jsonb,
 'marcus.thompson@example.com', '+14155551002'),

('Diana Patel', 'HL-2026-001249', 'Cancelled', false, false,
 'Downtown LA', 'J. Smith', 7, true, null,
 'State Farm', '6d 1h', 'hrd', '7d 3h', 'Unable to reach',
 '2026-01-28T09:15:00',
 '[{"time":"Jan 27, 3:00 PM","event":"Call","outcome":"No answer"},{"time":"Jan 28, 9:15 AM","event":"Call","outcome":"Voicemail"}]'::jsonb,
 null, '[]'::jsonb,
 null, '+14155551003'),

('Kevin O''Brien', 'HL-2026-001250', 'Rented', false, true,
 'Downtown LA', 'J. Smith', 1, false, null,
 'USAA', '20m', 'branch', null, null,
 '2026-02-03T09:45:00',
 '[{"time":"Feb 3, 9:45 AM","event":"Call","outcome":"Converted"}]'::jsonb,
 '{}'::jsonb, '[]'::jsonb,
 'kevin.obrien@example.com', '+14155551004'),

-- ── Santa Monica  (M. Johnson) ──────────────────────────────────────
('Yuki Tanaka', 'HL-2026-001251', 'Unused', false, false,
 'Santa Monica', 'M. Johnson', 5, false, null,
 'Allstate', null, 'none', null, null,
 null,
 '[]'::jsonb, null, '[]'::jsonb,
 'yuki.tanaka@example.com', null),

('Carlos Mendez', 'HL-2026-001252', 'Cancelled', false, true,
 'Santa Monica', 'M. Johnson', 2, false, null,
 'Farmers', '1h 30m', 'branch', '1d 10h', null,
 '2026-02-06T16:00:00',
 '[{"time":"Feb 5, 10:30 AM","event":"Call","outcome":"Spoke — needs docs"},{"time":"Feb 6, 4:00 PM","event":"Call","outcome":"Customer cancelled — missing paperwork"}]'::jsonb,
 '{"reason":"Documentation issues — could not complete","notes":"Customer unable to provide insurance docs","nextAction":"Close — no further action","followUpDate":null}'::jsonb,
 '[]'::jsonb,
 'carlos.mendez@example.com', '+14155551006'),

('Stephanie Brooks', 'HL-2026-001253', 'Rented', false, true,
 'Santa Monica', 'M. Johnson', 1, false, null,
 'Liberty Mutual', '40m', 'branch', null, null,
 '2026-02-10T11:20:00',
 '[{"time":"Feb 10, 11:20 AM","event":"Call","outcome":"Converted"}]'::jsonb,
 '{}'::jsonb, '[]'::jsonb,
 'stephanie.brooks@example.com', '+14155551007'),

-- ── Pasadena  (A. Garcia) ───────────────────────────────────────────
('Derek Washington', 'HL-2026-001254', 'Cancelled', false, false,
 'Pasadena', 'A. Garcia', 4, false, null,
 'Nationwide', '3d 4h', 'hrd', '4d 2h', 'Unable to reach',
 '2026-01-29T15:00:00',
 '[{"time":"Jan 28, 2:00 PM","event":"Call","outcome":"No answer"},{"time":"Jan 29, 3:00 PM","event":"SMS","outcome":"Sent — no reply"}]'::jsonb,
 null, '[]'::jsonb,
 null, '+14155551008'),

('Priya Sharma', 'HL-2026-001255', 'Rented', false, true,
 'Pasadena', 'A. Garcia', 1, false, null,
 'Geico', '25m', 'branch', null, null,
 '2026-02-07T09:30:00',
 '[{"time":"Feb 7, 9:30 AM","event":"Call","outcome":"Converted"}]'::jsonb,
 '{}'::jsonb, '[]'::jsonb,
 'priya.sharma@example.com', '+14155551009'),

('Nathan Foster', 'HL-2026-001256', 'Cancelled', false, true,
 'Pasadena', 'A. Garcia', 3, false, null,
 'State Farm', '2h 15m', 'branch', '2d 8h', 'Customer no-show',
 '2026-02-12T10:00:00',
 '[{"time":"Feb 10, 9:00 AM","event":"Call","outcome":"Spoke — confirmed"},{"time":"Feb 12, 10:00 AM","event":"Call","outcome":"No show"}]'::jsonb,
 '{"reason":"No-show after confirmation","notes":"Confirmed but did not show at branch","nextAction":"Send follow-up SMS","followUpDate":"Feb 18, 2026"}'::jsonb,
 '[]'::jsonb,
 'nathan.foster@example.com', '+14155551010'),

-- ── Long Beach  (S. Lee) ────────────────────────────────────────────
('Olivia Hughes', 'HL-2026-001257', 'Unused', false, false,
 'Long Beach', 'S. Lee', 6, false, null,
 'Progressive', null, 'none', null, null,
 null,
 '[]'::jsonb, null, '[]'::jsonb,
 'olivia.hughes@example.com', '+14155551011'),

('Brandon Scott', 'HL-2026-001258', 'Rented', false, true,
 'Long Beach', 'S. Lee', 2, false, null,
 'Allstate', '55m', 'branch', null, null,
 '2026-02-05T14:00:00',
 '[{"time":"Feb 4, 3:00 PM","event":"Call","outcome":"Spoke — rescheduled"},{"time":"Feb 5, 2:00 PM","event":"Call","outcome":"Converted"}]'::jsonb,
 '{}'::jsonb, '[]'::jsonb,
 'brandon.scott@example.com', '+14155551012'),

('Samantha Reese', 'HL-2026-001259', 'Cancelled', false, true,
 'Long Beach', 'S. Lee', 4, false, null,
 'Farmers', '3h 20m', 'branch', '3d 5h', null,
 '2026-02-09T11:30:00',
 '[{"time":"Feb 6, 11:00 AM","event":"Call","outcome":"Spoke — needs time"},{"time":"Feb 8, 2:00 PM","event":"SMS","outcome":"Sent reminder"},{"time":"Feb 9, 11:30 AM","event":"Call","outcome":"Customer chose competitor"}]'::jsonb,
 '{"reason":"Rented from competitor","notes":"Customer found lower rate at Enterprise","nextAction":"Close — no further action","followUpDate":null}'::jsonb,
 '[]'::jsonb,
 null, '+14155551013'),

-- ── Anaheim  (T. Brown) ─────────────────────────────────────────────
('Tyler Morgan', 'HL-2026-001260', 'Rented', false, true,
 'Anaheim', 'T. Brown', 1, false, null,
 'USAA', '15m', 'branch', null, null,
 '2026-02-14T10:15:00',
 '[{"time":"Feb 14, 10:15 AM","event":"Call","outcome":"Converted"}]'::jsonb,
 '{}'::jsonb, '[]'::jsonb,
 'tyler.morgan@example.com', '+14155551014'),

('Jessica Ruiz', 'HL-2026-001261', 'Cancelled', false, false,
 'Anaheim', 'T. Brown', 8, true, null,
 'Geico', '7d 3h', 'hrd', '8d 1h', 'Unable to reach',
 '2026-02-22T09:00:00',
 '[{"time":"Feb 21, 4:00 PM","event":"Call","outcome":"No answer"},{"time":"Feb 22, 9:00 AM","event":"Call","outcome":"Disconnected number"}]'::jsonb,
 null, '[]'::jsonb,
 null, null),

('Aiden Campbell', 'HL-2026-001262', 'Rented', false, true,
 'Anaheim', 'T. Brown', 1, false, null,
 'State Farm', '30m', 'branch', null, null,
 '2026-02-17T13:45:00',
 '[{"time":"Feb 17, 1:45 PM","event":"Call","outcome":"Converted"}]'::jsonb,
 '{}'::jsonb, '[]'::jsonb,
 'aiden.campbell@example.com', '+14155551016'),

('Monica Flores', 'HL-2026-001263', 'Cancelled', false, true,
 'Anaheim', 'T. Brown', 3, false, null,
 'Progressive', '1h 50m', 'branch', '2d 7h', 'Customer no-show',
 '2026-02-19T15:30:00',
 '[{"time":"Feb 17, 10:00 AM","event":"Call","outcome":"Spoke — confirmed Friday"},{"time":"Feb 19, 3:30 PM","event":"Call","outcome":"No show — no answer"}]'::jsonb,
 '{"reason":"No-show after confirmation","notes":"Confirmed for Friday, never showed","nextAction":"Call again","followUpDate":"Feb 25, 2026"}'::jsonb,
 '[]'::jsonb,
 'monica.flores@example.com', '+14155551017'),

-- ── San Diego Central  (R. Davis) ───────────────────────────────────
('Gregory Pierce', 'HL-2026-001264', 'Unused', false, false,
 'San Diego Central', 'R. Davis', 5, false, null,
 'Allstate', null, 'none', null, null,
 null,
 '[]'::jsonb, null, '[]'::jsonb,
 'gregory.pierce@example.com', null),

('Hannah Mitchell', 'HL-2026-001265', 'Rented', false, true,
 'San Diego Central', 'R. Davis', 1, false, null,
 'Liberty Mutual', '45m', 'branch', null, null,
 '2026-02-11T10:30:00',
 '[{"time":"Feb 11, 10:30 AM","event":"Call","outcome":"Converted"}]'::jsonb,
 '{}'::jsonb, '[]'::jsonb,
 'hannah.mitchell@example.com', '+14155551019'),

('Vincent Tran', 'HL-2026-001266', 'Cancelled', false, true,
 'San Diego Central', 'R. Davis', 2, false, null,
 'Nationwide', '1h 10m', 'branch', '1d 8h', null,
 '2026-02-15T16:20:00',
 '[{"time":"Feb 14, 2:00 PM","event":"Call","outcome":"Spoke — delayed"},{"time":"Feb 15, 4:20 PM","event":"Call","outcome":"Customer cancelled — changed travel plans"}]'::jsonb,
 '{"reason":"Changed travel plans","notes":"Customer postponed trip indefinitely","nextAction":"Close — no further action","followUpDate":null}'::jsonb,
 '[]'::jsonb,
 'vincent.tran@example.com', '+14155551020'),

('Danielle Cooper', 'HL-2026-001267', 'Rented', false, true,
 'San Diego Central', 'R. Davis', 1, false, null,
 'Farmers', '20m', 'branch', null, null,
 '2026-02-18T09:00:00',
 '[{"time":"Feb 18, 9:00 AM","event":"Call","outcome":"Converted"}]'::jsonb,
 '{}'::jsonb, '[]'::jsonb,
 'danielle.cooper@example.com', '+14155551021'),

-- ── La Jolla  (E. Wilson) ───────────────────────────────────────────
('Ryan Sullivan', 'HL-2026-001268', 'Unused', false, false,
 'La Jolla', 'E. Wilson', 4, false, null,
 'Geico', '1h 15m', 'branch', null, null,
 '2026-02-08T14:45:00',
 '[{"time":"Feb 8, 2:45 PM","event":"Call","outcome":"Left voicemail — awaiting callback"}]'::jsonb,
 null, '[]'::jsonb,
 null, '+14155551022'),

('Cynthia Yamamoto', 'HL-2026-001269', 'Cancelled', false, false,
 'La Jolla', 'E. Wilson', 6, false, null,
 'State Farm', '5d 2h', 'hrd', '6d 4h', 'Unable to reach',
 '2026-02-14T11:00:00',
 '[{"time":"Feb 13, 9:00 AM","event":"Call","outcome":"No answer"},{"time":"Feb 14, 11:00 AM","event":"Call","outcome":"Voicemail — mailbox full"}]'::jsonb,
 null, '[]'::jsonb,
 'cynthia.yamamoto@example.com', '+14155551023'),

('Patrick Doyle', 'HL-2026-001270', 'Rented', false, true,
 'La Jolla', 'E. Wilson', 1, false, null,
 'Progressive', '35m', 'branch', null, null,
 '2026-02-19T11:15:00',
 '[{"time":"Feb 19, 11:15 AM","event":"Call","outcome":"Converted"}]'::jsonb,
 '{}'::jsonb, '[]'::jsonb,
 'patrick.doyle@example.com', '+14155551024'),

-- ── Carlsbad  (P. Taylor) ───────────────────────────────────────────
('Megan Reyes', 'HL-2026-001271', 'Cancelled', false, true,
 'Carlsbad', 'P. Taylor', 3, false, null,
 'USAA', '2h 30m', 'branch', '2d 5h', null,
 '2026-02-07T13:00:00',
 '[{"time":"Feb 5, 9:30 AM","event":"Call","outcome":"Spoke — checking availability"},{"time":"Feb 7, 1:00 PM","event":"Call","outcome":"Customer found better rate"}]'::jsonb,
 '{"reason":"Found better rate elsewhere","notes":"Customer got quote from Budget","nextAction":"Close — no further action","followUpDate":null}'::jsonb,
 '[]'::jsonb,
 'megan.reyes@example.com', '+14155551025'),

('Jamal Edwards', 'HL-2026-001272', 'Rented', false, true,
 'Carlsbad', 'P. Taylor', 2, false, null,
 'Allstate', '50m', 'branch', null, null,
 '2026-02-13T15:30:00',
 '[{"time":"Feb 12, 2:00 PM","event":"Call","outcome":"Spoke — needs SUV"},{"time":"Feb 13, 3:30 PM","event":"Call","outcome":"Converted — upgraded to SUV"}]'::jsonb,
 '{}'::jsonb, '[]'::jsonb,
 'jamal.edwards@example.com', '+14155551026'),

('Katherine Barnes', 'HL-2026-001273', 'Cancelled', false, true,
 'Carlsbad', 'P. Taylor', 2, false, null,
 'Farmers', '1h 20m', 'branch', '1d 9h', 'Customer no-show',
 '2026-02-20T10:45:00',
 '[{"time":"Feb 19, 11:00 AM","event":"Call","outcome":"Spoke — confirmed"},{"time":"Feb 20, 10:45 AM","event":"Call","outcome":"No show"}]'::jsonb,
 '{"reason":"No-show after confirmation","notes":"Confirmed but never arrived","nextAction":"Send follow-up SMS","followUpDate":"Feb 26, 2026"}'::jsonb,
 '[]'::jsonb,
 'katherine.barnes@example.com', '+14155551027'),

-- ── Mission Valley  (C. Anderson) ───────────────────────────────────
('Luke Henderson', 'HL-2026-001274', 'Unused', false, false,
 'Mission Valley', 'C. Anderson', 7, false, null,
 'State Farm', null, 'none', null, null,
 null,
 '[]'::jsonb, null, '[]'::jsonb,
 null, '+14155551028'),

('Sophia Castillo', 'HL-2026-001275', 'Rented', false, true,
 'Mission Valley', 'C. Anderson', 1, false, null,
 'Geico', '30m', 'branch', null, null,
 '2026-02-15T09:45:00',
 '[{"time":"Feb 15, 9:45 AM","event":"Call","outcome":"Converted"}]'::jsonb,
 '{}'::jsonb, '[]'::jsonb,
 'sophia.castillo@example.com', '+14155551029'),

('Elijah Gray', 'HL-2026-001276', 'Cancelled', false, false,
 'Mission Valley', 'C. Anderson', 9, true, null,
 'Progressive', '8d 1h', 'hrd', '9d 3h', 'Unable to reach',
 '2026-02-24T10:30:00',
 '[{"time":"Feb 23, 4:00 PM","event":"Call","outcome":"No answer"},{"time":"Feb 24, 10:30 AM","event":"Call","outcome":"Wrong number on file"}]'::jsonb,
 null, '[]'::jsonb,
 null, null),

-- ── Chula Vista  (N. Thomas) ────────────────────────────────────────
('Amanda Weiss', 'HL-2026-001277', 'Rented', false, true,
 'Chula Vista', 'N. Thomas', 1, false, null,
 'Liberty Mutual', '25m', 'branch', null, null,
 '2026-01-23T10:00:00',
 '[{"time":"Jan 23, 10:00 AM","event":"Call","outcome":"Converted"}]'::jsonb,
 '{}'::jsonb, '[]'::jsonb,
 'amanda.weiss@example.com', '+14155551031'),

('Darius Knight', 'HL-2026-001278', 'Cancelled', false, true,
 'Chula Vista', 'N. Thomas', 3, false, null,
 'Nationwide', '2h', 'branch', '2d 6h', null,
 '2026-01-28T16:00:00',
 '[{"time":"Jan 26, 10:00 AM","event":"Call","outcome":"Spoke — checking with insurance"},{"time":"Jan 28, 4:00 PM","event":"Call","outcome":"Insurance denied coverage"}]'::jsonb,
 '{"reason":"Other (see notes)","notes":"Insurance company denied rental coverage claim","nextAction":"Close — no further action","followUpDate":null}'::jsonb,
 '[]'::jsonb,
 'darius.knight@example.com', '+14155551032'),

('Rebecca Cho', 'HL-2026-001279', 'Rented', false, true,
 'Chula Vista', 'N. Thomas', 1, false, null,
 'Allstate', '40m', 'branch', null, null,
 '2026-02-04T13:30:00',
 '[{"time":"Feb 4, 1:30 PM","event":"Call","outcome":"Converted"}]'::jsonb,
 '{}'::jsonb, '[]'::jsonb,
 'rebecca.cho@example.com', '+14155551033'),

('Troy Patterson', 'HL-2026-001280', 'Cancelled', false, true,
 'Chula Vista', 'N. Thomas', 4, false, null,
 'State Farm', '3h 10m', 'branch', '3d 8h', null,
 '2026-02-11T11:45:00',
 '[{"time":"Feb 8, 10:00 AM","event":"Call","outcome":"Spoke — tentative"},{"time":"Feb 10, 2:00 PM","event":"SMS","outcome":"Sent confirmation link"},{"time":"Feb 11, 11:45 AM","event":"Call","outcome":"Customer decided not to rent"}]'::jsonb,
 '{"reason":"Decided not to rent","notes":"Customer said repairs completed sooner than expected","nextAction":"Close — no further action","followUpDate":null}'::jsonb,
 '[]'::jsonb,
 'troy.patterson@example.com', '+14155551034'),

-- ── Sacramento North  (B. Jackson) ──────────────────────────────────
('Vanessa Ortiz', 'HL-2026-001281', 'Unused', false, false,
 'Sacramento North', 'B. Jackson', 5, false, null,
 'Geico', null, 'none', null, null,
 null,
 '[]'::jsonb, null, '[]'::jsonb,
 null, '+14155551035'),

('Simon Hawkins', 'HL-2026-001282', 'Rented', false, true,
 'Sacramento North', 'B. Jackson', 1, false, null,
 'Farmers', '20m', 'branch', null, null,
 '2026-02-13T09:00:00',
 '[{"time":"Feb 13, 9:00 AM","event":"Call","outcome":"Converted"}]'::jsonb,
 '{}'::jsonb, '[]'::jsonb,
 'simon.hawkins@example.com', '+14155551036'),

('Laura Fernandez', 'HL-2026-001283', 'Cancelled', false, false,
 'Sacramento North', 'B. Jackson', 6, false, null,
 'Progressive', '5d 3h', 'hrd', '6d 1h', 'Unable to reach',
 '2026-02-21T14:00:00',
 '[{"time":"Feb 20, 11:00 AM","event":"Call","outcome":"No answer"},{"time":"Feb 21, 2:00 PM","event":"Call","outcome":"Voicemail"}]'::jsonb,
 null, '[]'::jsonb,
 'laura.fernandez@example.com', null),

-- ── Roseville  (D. White) ───────────────────────────────────────────
('Blake Turner', 'HL-2026-001284', 'Cancelled', false, true,
 'Roseville', 'D. White', 2, false, null,
 'USAA', '1h 40m', 'branch', '1d 10h', null,
 '2026-01-25T15:30:00',
 '[{"time":"Jan 24, 10:00 AM","event":"Call","outcome":"Spoke — needs minivan"},{"time":"Jan 25, 3:30 PM","event":"Call","outcome":"No minivan available — customer cancelled"}]'::jsonb,
 '{"reason":"Vehicle availability — customer declined alternative","notes":"Requested minivan, only sedans available","nextAction":"Close — no further action","followUpDate":null}'::jsonb,
 '[]'::jsonb,
 'blake.turner@example.com', '+14155551038'),

('Isabelle Dubois', 'HL-2026-001285', 'Rented', false, true,
 'Roseville', 'D. White', 1, false, null,
 'Allstate', '35m', 'branch', null, null,
 '2026-02-06T10:15:00',
 '[{"time":"Feb 6, 10:15 AM","event":"Call","outcome":"Converted"}]'::jsonb,
 '{}'::jsonb, '[]'::jsonb,
 'isabelle.dubois@example.com', '+14155551039'),

('Craig Simmons', 'HL-2026-001286', 'Cancelled', false, true,
 'Roseville', 'D. White', 3, false, null,
 'State Farm', '2h 45m', 'branch', '2d 4h', 'Customer no-show',
 '2026-02-16T09:30:00',
 '[{"time":"Feb 14, 9:00 AM","event":"Call","outcome":"Spoke — confirmed"},{"time":"Feb 16, 9:30 AM","event":"Call","outcome":"No show — unreachable"}]'::jsonb,
 '{"reason":"No-show after confirmation","notes":"Confirmed but never showed; phone goes to voicemail","nextAction":"Escalate to AM","followUpDate":"Feb 22, 2026"}'::jsonb,
 '[]'::jsonb,
 'craig.simmons@example.com', '+14155551040'),

-- ── Folsom  (F. Harris) ─────────────────────────────────────────────
('Alicia Romero', 'HL-2026-001287', 'Unused', false, false,
 'Folsom', 'F. Harris', 4, false, null,
 'Liberty Mutual', '1h', 'branch', null, null,
 '2026-02-02T11:00:00',
 '[{"time":"Feb 2, 11:00 AM","event":"Call","outcome":"Left voicemail — awaiting callback"}]'::jsonb,
 null, '[]'::jsonb,
 'alicia.romero@example.com', '+14155551041'),

('Wesley Chang', 'HL-2026-001288', 'Rented', false, true,
 'Folsom', 'F. Harris', 1, false, null,
 'Geico', '15m', 'branch', null, null,
 '2026-02-09T10:00:00',
 '[{"time":"Feb 9, 10:00 AM","event":"Call","outcome":"Converted"}]'::jsonb,
 '{}'::jsonb, '[]'::jsonb,
 'wesley.chang@example.com', '+14155551042'),

('Natalie Price', 'HL-2026-001289', 'Cancelled', false, true,
 'Folsom', 'F. Harris', 5, false, null,
 'Farmers', '4h 30m', 'branch', '4d 6h', null,
 '2026-02-18T14:00:00',
 '[{"time":"Feb 14, 11:00 AM","event":"Call","outcome":"Spoke — hesitant"},{"time":"Feb 16, 3:00 PM","event":"SMS","outcome":"Sent follow-up"},{"time":"Feb 18, 2:00 PM","event":"Call","outcome":"Customer rented from competitor"}]'::jsonb,
 '{"reason":"Rented from competitor","notes":"Customer rented from Avis at a lower daily rate","nextAction":"Close — no further action","followUpDate":null}'::jsonb,
 '[]'::jsonb,
 'natalie.price@example.com', '+14155551043'),

('Dominic Costa', 'HL-2026-001290', 'Rented', false, true,
 'Folsom', 'F. Harris', 2, false, null,
 'Nationwide', '50m', 'branch', null, null,
 '2026-02-22T15:00:00',
 '[{"time":"Feb 21, 3:00 PM","event":"Call","outcome":"Spoke — picking up tomorrow"},{"time":"Feb 22, 3:00 PM","event":"Call","outcome":"Converted"}]'::jsonb,
 '{}'::jsonb, '[]'::jsonb,
 'dominic.costa@example.com', '+14155551044'),

-- ── Elk Grove  (G. Clark) ───────────────────────────────────────────
('Julia Sanders', 'HL-2026-001291', 'Cancelled', false, false,
 'Elk Grove', 'G. Clark', 10, true, null,
 'Progressive', '9d 2h', 'hrd', '10d 1h', 'Unable to reach',
 '2026-02-25T09:00:00',
 '[{"time":"Feb 24, 3:00 PM","event":"Call","outcome":"No answer"},{"time":"Feb 25, 9:00 AM","event":"Call","outcome":"Number not in service"}]'::jsonb,
 null, '[]'::jsonb,
 null, null),

('Keith Nakamura', 'HL-2026-001292', 'Unused', false, false,
 'Elk Grove', 'G. Clark', 3, false, null,
 'Allstate', null, 'none', null, null,
 null,
 '[]'::jsonb, null, '[]'::jsonb,
 'keith.nakamura@example.com', '+14155551046'),

('Brittany Holmes', 'HL-2026-001293', 'Rented', false, true,
 'Elk Grove', 'G. Clark', 1, false, null,
 'State Farm', '30m', 'branch', null, null,
 '2026-02-20T11:30:00',
 '[{"time":"Feb 20, 11:30 AM","event":"Call","outcome":"Converted"}]'::jsonb,
 '{}'::jsonb, '[]'::jsonb,
 'brittany.holmes@example.com', '+14155551047'),

-- ── Davis  (H. Lewis) ───────────────────────────────────────────────
('Oscar Reeves', 'HL-2026-001294', 'Cancelled', false, true,
 'Davis', 'H. Lewis', 4, false, null,
 'USAA', '3h 15m', 'branch', '3d 6h', null,
 '2026-02-12T16:45:00',
 '[{"time":"Feb 9, 10:00 AM","event":"Call","outcome":"Spoke — checking with spouse"},{"time":"Feb 11, 1:00 PM","event":"SMS","outcome":"Sent reminder"},{"time":"Feb 12, 4:45 PM","event":"Call","outcome":"Customer changed travel plans"}]'::jsonb,
 '{"reason":"Changed travel plans","notes":"Family trip cancelled","nextAction":"Close — no further action","followUpDate":null}'::jsonb,
 '[]'::jsonb,
 'oscar.reeves@example.com', '+14155551048'),

('Claire Jimenez', 'HL-2026-001295', 'Rented', false, true,
 'Davis', 'H. Lewis', 1, false, null,
 'Geico', '25m', 'branch', null, null,
 '2026-02-21T09:30:00',
 '[{"time":"Feb 21, 9:30 AM","event":"Call","outcome":"Converted"}]'::jsonb,
 '{}'::jsonb, '[]'::jsonb,
 'claire.jimenez@example.com', '+14155551049'),

('Mitchell Flynn', 'HL-2026-001296', 'Cancelled', false, false,
 'Davis', 'H. Lewis', 5, false, null,
 'Farmers', '4d 6h', 'hrd', '5d 2h', 'Unable to reach',
 '2026-02-23T15:30:00',
 '[{"time":"Feb 22, 10:00 AM","event":"Call","outcome":"No answer"},{"time":"Feb 23, 3:30 PM","event":"Call","outcome":"Voicemail"}]'::jsonb,
 null, '[]'::jsonb,
 null, '+14155551050');


-- ── Additional tasks for some of the new leads ──────────────────────
-- (Uses lead IDs that will depend on current max ID; adjust if needed)
-- These reference the new leads by reservation_id subquery

INSERT INTO public.tasks (
  title, description, notes, due_date, status, priority,
  lead_id, source, created_by_name, assigned_to_name
)
SELECT
  t.title, t.description, t.notes, t.due_date::date, t.status, t.priority,
  l.id, t.source, t.created_by_name, t.assigned_to_name
FROM (VALUES
  ('Follow up on Diana Patel cancellation',
   'No BM comments despite 7-day-old cancelled lead — enrichment required',
   null, '2026-03-01', 'Open', 'High',
   'HL-2026-001249', 'gm_assigned', 'D. Williams', 'J. Smith'),
  ('Contact Jessica Ruiz — disconnected number',
   'Phone disconnected — try alternate contact or escalate',
   null, '2026-02-28', 'Open', 'High',
   'HL-2026-001261', 'gm_assigned', 'D. Williams', 'T. Brown'),
  ('Review Elijah Gray mismatch',
   '9 days open — wrong number on file, needs resolution',
   null, '2026-02-27', 'Open', 'High',
   'HL-2026-001276', 'gm_assigned', 'R. Martinez', 'C. Anderson'),
  ('Enrich Julia Sanders lead',
   '10 days with no enrichment — number not in service',
   null, '2026-02-28', 'Open', 'High',
   'HL-2026-001291', 'gm_assigned', 'R. Martinez', 'G. Clark'),
  ('Follow up Laura Fernandez voicemail',
   'HRD contacted first — branch needs to take over follow-up',
   'Left two voicemails so far, no response.', '2026-03-01', 'In Progress', 'Medium',
   'HL-2026-001283', 'gm_assigned', 'R. Martinez', 'B. Jackson')
) AS t(title, description, notes, due_date, status, priority, res_id, source, created_by_name, assigned_to_name)
JOIN public.leads l ON l.reservation_id = t.res_id;
